# https://docs.astral.sh/ruff/settings/#output-format
output-format = "grouped"

indent-width = 4
line-length = 110

target-version = "py312"
src = ['.', 'wood', 'wood/src', 'wood/test']

exclude = [".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".mypy_cache", ".nox", ".pants.d", ".pytype", ".ruff_cache", ".svn", ".tox", ".venv", "__pypackages__", "_build", "buck-out", "dist", "node_modules", "venv"]
extend-exclude = []
include = ["*.py", "*.pyi", "*.ipynb", "**/pyproject.toml"]
extend-include = []

[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true
# Format all docstring code snippets with a line length of X.
docstring-code-line-length = "dynamic"
# Other
indent-style = "space"
line-ending = "auto"
quote-style = "preserve"
skip-magic-trailing-comma = false

[lint.flake8-annotations]
allow-star-arg-any = false
ignore-fully-untyped = false
mypy-init-return = false
suppress-dummy-args = false
suppress-none-returning = false

[lint.flake8-quotes]
# Don't bother trying to avoid escapes.
avoid-escape = true
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"